sudo: required

dist: trusty

language: cpp

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq build-essential ruby-dev
 - sudo apt-get install -qq libqt4-dev zlib1g-dev libpoppler-qt4-dev
 - sudo gem install fpm

script:
 - qmake texmaker.pro "VERSION=$TRAVIS_TAG"
 - make
 - sudo make install

before_deploy:
 - sudo fpm -s dir -t deb -n texmaker-kostrykin -v "$TRAVIS_TAG" -d libqt4 -d zlib1g -d libpoppler-qt4 --prefix /usr/bin texmaker

deploy:
  provider: releases
  api_key:
    secure: yQFoKkwRRVFOnNgALnVaDWloJvwBK9FsTW4uCQSLLd71+X2tgWI8t3En6FRKSsUM9tllq9Q7Z+qD+B5PidLSYPHIxLLG9O6X4KTl47FkhBvbNi0CUM8iKy6wiVS8rOAnb+0pO5O7uXICtnaUh+MP9LPmQJDZv1DlBTuS1YfiixFOUDS9pbMk3eKLi/AKgRh1a23hcfaTbAcxaEY3xa9WS1jw/vVwoE9sihdVw0hYwY8T6qe/P5tbVVE5hJ5JRWbMNr+oatA9pc+hpaVKzV70+nlx4wjkX3bymDSCGpOzKP5UQ8ELb6tXsYC8IRJiYurwQx0Hfp3CO7aRj6UKX1Vz9Jmu1o5o6Wc9t2hioN30o3G0xLGd+/bsqWDu3p824Ajy/oWneG7wD8Hw8LOULNuYMM5lpQrkdvyrFRkkKrjkeJyJYJkEULh2LXbFROpZcW8jb4C+Wx7WFKr8oINFpnpGbDXF408X2deSyfxVeZ7umPO4j4VNeNLm5aul7Dq3RBEPq41QnwAhanVOrP4UcQ2W0u1vsEm8KhJhtL0FG+tmde72LIlu5U2ddsV2n0paBN/2LFtIYYndMpiIXczdnyJaQJ0BG/Hwut7hC6YVFjDd1PAgY92jmJYTe3Xgfk5diZLRZ00IIy8b+6I/SF52y1xXoIcbrL59ykArD9Jc7aIz7hA=
  file: $(ls *.deb)
  skip_cleanup: true
  on:
    tags: true
